version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: django_dev
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - arangodb

  arangodb:
    image: arangodb:latest
    container_name: arangodb_dev
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_DB_PASSWORD}
    ports:
      - "8529:8529"
    volumes:
      - arangodata:/var/lib/arangodb3

volumes:
  arangodata:
