version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django_prod
    env_file: .env.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - arangodb

  arangodb:
    image: arangodb:latest
    container_name: arangodb_prod
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_DB_PASSWORD}
    ports:
      - "8529:8529"
    volumes:
      - arangodata:/var/lib/arangodb3

volumes:
  arangodata:
